### PR TITLE
Fix the missing return type issue in generated Swift action

### LINKED ISSUE #7: Generated action in Swift doesn't have return type
Currently, the generated action in Swift is this:
```
/**
 Jira release notes

 - parameters:
   - url: URL for Jira instance
   - username: Username for Jira instance
   - password: Password or api token for Jira
   - project: Jira project name
   - status: Jira issue status
   - version: Jira project version
   - format: Format text. Plain, html or none
   - maxResults: Maximum number of issues

 - returns: List of issues from jira. Formatted string or class

 Fetch release notes for Jira project for version
*/
public func jiraReleaseNotes(url: String,
                             username: String,
                             password: String,
                             project: String,
                             status: String,
                             version: Any,
                             format: String,
                             maxResults: String = "50") {
let urlArg = RubyCommand.Argument(name: "url", value: url, type: nil)
let usernameArg = RubyCommand.Argument(name: "username", value: username, type: nil)
let passwordArg = RubyCommand.Argument(name: "password", value: password, type: nil)
let projectArg = RubyCommand.Argument(name: "project", value: project, type: nil)
let statusArg = RubyCommand.Argument(name: "status", value: status, type: nil)
let versionArg = RubyCommand.Argument(name: "version", value: version, type: nil)
let formatArg = RubyCommand.Argument(name: "format", value: format, type: nil)
let maxResultsArg = RubyCommand.Argument(name: "max_results", value: maxResults, type: nil)
let array: [RubyCommand.Argument?] = [urlArg,
usernameArg,
passwordArg,
projectArg,
statusArg,
versionArg,
formatArg,
maxResultsArg]
let args: [RubyCommand.Argument] = array
.filter { $0?.value != nil }
.compactMap { $0 }
let command = RubyCommand(commandID: "", methodName: "jira_release_notes", className: nil, args: args)
  _ = runner.executeCommand(command)
}
```

As we can see, the function doesn't return any value.
I found the root cause and will create a PR soon.

### PR DESCRIPTION
**Pull request by kienw**
Fixed #7 

Here is the generated Swift action:
```
/**
 Jira release notes

 - parameters:
   - url: URL for Jira instance
   - username: Username for Jira instance
   - password: Password or api token for Jira
   - project: Jira project name
   - status: Jira issue status
   - version: Jira project version
   - format: Format text. Plain, html or none
   - maxResults: Maximum number of issues

 - returns: List of issues from jira. Formatted string or class

 Fetch release notes for Jira project for version
*/
@discardableResult public func jiraReleaseNotes(url: String,
                                                username: String,
                                                password: String,
                                                project: String,
                                                status: String,
                                                version: Any,
                                                format: String,
                                                maxResults: String = "50") -> String {
let urlArg = RubyCommand.Argument(name: "url", value: url, type: nil)
let usernameArg = RubyCommand.Argument(name: "username", value: username, type: nil)
let passwordArg = RubyCommand.Argument(name: "password", value: password, type: nil)
let projectArg = RubyCommand.Argument(name: "project", value: project, type: nil)
let statusArg = RubyCommand.Argument(name: "status", value: status, type: nil)
let versionArg = RubyCommand.Argument(name: "version", value: version, type: nil)
let formatArg = RubyCommand.Argument(name: "format", value: format, type: nil)
let maxResultsArg = RubyCommand.Argument(name: "max_results", value: maxResults, type: nil)
let array: [RubyCommand.Argument?] = [urlArg,
usernameArg,
passwordArg,
projectArg,
statusArg,
versionArg,
formatArg,
maxResultsArg]
let args: [RubyCommand.Argument] = array
.filter { $0?.value != nil }
.compactMap { $0 }
let command = RubyCommand(commandID: "", methodName: "jira_release_notes", className: nil, args: args)
  return runner.executeCommand(command)
}
```

### CODE REVIEW

**Comment by vani2** [comment]
@Alexander-Ignition take a look.

**Comment by Alexander-Ignition** [comment]
@kien-huubap thanks for the interesting example

but the string is returned only for plain and html formats
if the format is not specified, objects from jira-ruby will be returned

I think if there is no option that suits different formats , it will just be a string

**Comment by kienw** [comment]
> @kien-huubap thanks for the interesting example
> 
> but the string is returned only for plain and html formats
> if the format is not specified, objects from jira-ruby will be returned
> 
> I think if there is no option that suits different formats , it will just be a string

Oh yeah, you are right. I missed that.

Probably fastlane need to support more types.
https://github.com/fastlane/fastlane/blob/e874a47c6e2e0e61590a03d3b71e75e5a505d1ce/fastlane/lib/fastlane/action.rb#L23

**Comment by Alexander-Ignition** [comment]
I think that `:string` is now suitable

**Review by Alexander-Ignition — APPROVED** [review]

**Pull request merged**
